@extends('layouts.site')
@section('head')
    @include('site.head')
@endsection
@section('content')
    @include('site.content-thanks')
@endsection
@section('footer')
    @include('site.footer')
@endsection
@section('scripts')
    @include('site.scripts')
@endsection